// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/hightouch-go-sdk/pkg/models/shared"
	"net/http"
)

type GetModelRequest struct {
	// The id of the model
	ModelID float64 `pathParam:"style=simple,explode=false,name=modelId"`
}

func (o *GetModelRequest) GetModelID() float64 {
	if o == nil {
		return 0.0
	}
	return o.ModelID
}

type GetModelResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Ok
	Model *shared.Model
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetModelResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetModelResponse) GetModel() *shared.Model {
	if o == nil {
		return nil
	}
	return o.Model
}

func (o *GetModelResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetModelResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
