// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/hightouch-go-sdk/pkg/models/shared"
	"net/http"
)

type GetSyncSequenceRunRequest struct {
	// The id of the sync sequence run
	SyncSequenceRunID string `pathParam:"style=simple,explode=false,name=syncSequenceRunId"`
}

func (o *GetSyncSequenceRunRequest) GetSyncSequenceRunID() string {
	if o == nil {
		return ""
	}
	return o.SyncSequenceRunID
}

type GetSyncSequenceRunResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Ok
	SyncSequenceStatusOutput *shared.SyncSequenceStatusOutput
	// Validation Failed
	ValidateErrorJSON *shared.ValidateErrorJSON
}

func (o *GetSyncSequenceRunResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSyncSequenceRunResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSyncSequenceRunResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetSyncSequenceRunResponse) GetSyncSequenceStatusOutput() *shared.SyncSequenceStatusOutput {
	if o == nil {
		return nil
	}
	return o.SyncSequenceStatusOutput
}

func (o *GetSyncSequenceRunResponse) GetValidateErrorJSON() *shared.ValidateErrorJSON {
	if o == nil {
		return nil
	}
	return o.ValidateErrorJSON
}
