// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/hightouch-go-sdk/pkg/models/shared"
	"net/http"
)

type ListDestinationSecurity struct {
	BearerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

// ListDestinationOrderBy - Order the returned destinations
type ListDestinationOrderBy string

const (
	ListDestinationOrderByID        ListDestinationOrderBy = "id"
	ListDestinationOrderByName      ListDestinationOrderBy = "name"
	ListDestinationOrderBySlug      ListDestinationOrderBy = "slug"
	ListDestinationOrderByCreatedAt ListDestinationOrderBy = "createdAt"
	ListDestinationOrderByUpdatedAt ListDestinationOrderBy = "updatedAt"
)

func (e ListDestinationOrderBy) ToPointer() *ListDestinationOrderBy {
	return &e
}

func (e *ListDestinationOrderBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "name":
		fallthrough
	case "slug":
		fallthrough
	case "createdAt":
		fallthrough
	case "updatedAt":
		*e = ListDestinationOrderBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListDestinationOrderBy: %v", v)
	}
}

type ListDestinationRequest struct {
	// limit the number of objects returned (default is 100)
	Limit *float64 `queryParam:"style=form,explode=true,name=limit"`
	// Filter based on the destination's name
	Name *string `queryParam:"style=form,explode=true,name=name"`
	// set the offset on results (for pagination)
	Offset *float64 `queryParam:"style=form,explode=true,name=offset"`
	// Order the returned destinations
	OrderBy *ListDestinationOrderBy `queryParam:"style=form,explode=true,name=orderBy"`
	// Filter based on destination's slug
	Slug *string `queryParam:"style=form,explode=true,name=slug"`
}

// ListDestination200ApplicationJSON - Ok
type ListDestination200ApplicationJSON struct {
	Data []shared.Destination `json:"data"`
}

type ListDestinationResponse struct {
	ContentType string
	// Ok
	ListDestination200ApplicationJSONObject *ListDestination200ApplicationJSON
	StatusCode                              int
	RawResponse                             *http.Response
	// Validation Failed
	ValidateErrorJSON *shared.ValidateErrorJSON
}
