// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/hightouch-go-sdk/pkg/models/shared"
	"net/http"
)

type ListModelSecurity struct {
	BearerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

// ListModelOrderByEnum - specify the order
type ListModelOrderByEnum string

const (
	ListModelOrderByEnumID        ListModelOrderByEnum = "id"
	ListModelOrderByEnumName      ListModelOrderByEnum = "name"
	ListModelOrderByEnumSlug      ListModelOrderByEnum = "slug"
	ListModelOrderByEnumCreatedAt ListModelOrderByEnum = "createdAt"
	ListModelOrderByEnumUpdatedAt ListModelOrderByEnum = "updatedAt"
)

type ListModelRequest struct {
	// limit the number of objects returned (default is 100)
	Limit *float64 `queryParam:"style=form,explode=true,name=limit"`
	// filter based on name
	Name *string `queryParam:"style=form,explode=true,name=name"`
	// set the offset on results (for pagination)
	Offset *float64 `queryParam:"style=form,explode=true,name=offset"`
	// specify the order
	OrderBy *ListModelOrderByEnum `queryParam:"style=form,explode=true,name=orderBy"`
	// filter based on slug
	Slug *string `queryParam:"style=form,explode=true,name=slug"`
}

// ListModel200ApplicationJSON - Ok
type ListModel200ApplicationJSON struct {
	Data []shared.Model `json:"data"`
}

type ListModelResponse struct {
	ContentType string
	// Ok
	ListModel200ApplicationJSONObject *ListModel200ApplicationJSON
	StatusCode                        int
	RawResponse                       *http.Response
	// Validation Failed
	ValidateErrorJSON *shared.ValidateErrorJSON
}
