// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/hightouch-go-sdk/pkg/models/shared"
	"github.com/speakeasy-sdks/hightouch-go-sdk/pkg/utils"
	"net/http"
	"time"
)

// ListSyncRunsOrderBy - specify the order
type ListSyncRunsOrderBy string

const (
	ListSyncRunsOrderByID         ListSyncRunsOrderBy = "id"
	ListSyncRunsOrderByCreatedAt  ListSyncRunsOrderBy = "createdAt"
	ListSyncRunsOrderByStartedAt  ListSyncRunsOrderBy = "startedAt"
	ListSyncRunsOrderByFinishedAt ListSyncRunsOrderBy = "finishedAt"
)

func (e ListSyncRunsOrderBy) ToPointer() *ListSyncRunsOrderBy {
	return &e
}

func (e *ListSyncRunsOrderBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "createdAt":
		fallthrough
	case "startedAt":
		fallthrough
	case "finishedAt":
		*e = ListSyncRunsOrderBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListSyncRunsOrderBy: %v", v)
	}
}

type ListSyncRunsRequest struct {
	// select sync runs that are started after given ISO timestamp
	After *time.Time `queryParam:"style=form,explode=true,name=after"`
	// select sync runs that are started before certain ISO timestamp
	Before *time.Time `queryParam:"style=form,explode=true,name=before"`
	// limit the number of objects returned (default is 5)
	Limit *float64 `default:"100" queryParam:"style=form,explode=true,name=limit"`
	// set the offset on results (for pagination)
	Offset *float64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
	// specify the order
	OrderBy *ListSyncRunsOrderBy `default:"id" queryParam:"style=form,explode=true,name=orderBy"`
	// query for specific run id
	RunID  *float64 `queryParam:"style=form,explode=true,name=runId"`
	SyncID float64  `pathParam:"style=simple,explode=false,name=syncId"`
	// select sync runs that are started within last given minutes
	Within *float64 `queryParam:"style=form,explode=true,name=within"`
}

func (l ListSyncRunsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSyncRunsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListSyncRunsRequest) GetAfter() *time.Time {
	if o == nil {
		return nil
	}
	return o.After
}

func (o *ListSyncRunsRequest) GetBefore() *time.Time {
	if o == nil {
		return nil
	}
	return o.Before
}

func (o *ListSyncRunsRequest) GetLimit() *float64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListSyncRunsRequest) GetOffset() *float64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *ListSyncRunsRequest) GetOrderBy() *ListSyncRunsOrderBy {
	if o == nil {
		return nil
	}
	return o.OrderBy
}

func (o *ListSyncRunsRequest) GetRunID() *float64 {
	if o == nil {
		return nil
	}
	return o.RunID
}

func (o *ListSyncRunsRequest) GetSyncID() float64 {
	if o == nil {
		return 0.0
	}
	return o.SyncID
}

func (o *ListSyncRunsRequest) GetWithin() *float64 {
	if o == nil {
		return nil
	}
	return o.Within
}

// ListSyncRuns200ApplicationJSON - Ok
type ListSyncRuns200ApplicationJSON struct {
	Data    []shared.SyncRun `json:"data"`
	HasMore bool             `json:"hasMore"`
}

func (o *ListSyncRuns200ApplicationJSON) GetData() []shared.SyncRun {
	if o == nil {
		return []shared.SyncRun{}
	}
	return o.Data
}

func (o *ListSyncRuns200ApplicationJSON) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

type ListSyncRunsResponse struct {
	ContentType string
	// Ok
	ListSyncRuns200ApplicationJSONObject *ListSyncRuns200ApplicationJSON
	StatusCode                           int
	RawResponse                          *http.Response
	// Validation Failed
	ValidateErrorJSON *shared.ValidateErrorJSON
}

func (o *ListSyncRunsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListSyncRunsResponse) GetListSyncRuns200ApplicationJSONObject() *ListSyncRuns200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.ListSyncRuns200ApplicationJSONObject
}

func (o *ListSyncRunsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListSyncRunsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListSyncRunsResponse) GetValidateErrorJSON() *shared.ValidateErrorJSON {
	if o == nil {
		return nil
	}
	return o.ValidateErrorJSON
}
