// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/hightouch-go-sdk/pkg/models/shared"
	"net/http"
)

type TriggerRunIDGraphSecurity struct {
	BearerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (o *TriggerRunIDGraphSecurity) GetBearerAuth() string {
	if o == nil {
		return ""
	}
	return o.BearerAuth
}

type TriggerRunIDGraphRequest struct {
	TriggerRunIDGraphInput *shared.TriggerRunIDGraphInput `request:"mediaType=application/json"`
	GraphID                string                         `pathParam:"style=simple,explode=false,name=graphId"`
}

func (o *TriggerRunIDGraphRequest) GetTriggerRunIDGraphInput() *shared.TriggerRunIDGraphInput {
	if o == nil {
		return nil
	}
	return o.TriggerRunIDGraphInput
}

func (o *TriggerRunIDGraphRequest) GetGraphID() string {
	if o == nil {
		return ""
	}
	return o.GraphID
}

type TriggerRunIDGraphResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Ok
	TriggerRunIDGraphOutput *shared.TriggerRunIDGraphOutput
	// Validation Failed
	ValidateErrorJSON *shared.ValidateErrorJSON
}

func (o *TriggerRunIDGraphResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *TriggerRunIDGraphResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *TriggerRunIDGraphResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *TriggerRunIDGraphResponse) GetTriggerRunIDGraphOutput() *shared.TriggerRunIDGraphOutput {
	if o == nil {
		return nil
	}
	return o.TriggerRunIDGraphOutput
}

func (o *TriggerRunIDGraphResponse) GetValidateErrorJSON() *shared.ValidateErrorJSON {
	if o == nil {
		return nil
	}
	return o.ValidateErrorJSON
}
