// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/hightouch-go-sdk/pkg/models/shared"
	"net/http"
)

type UpdateModelSecurity struct {
	BearerAuth string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type UpdateModelRequest struct {
	ModelUpdate shared.ModelUpdate `request:"mediaType=application/json"`
	// The model's ID
	ModelID float64 `pathParam:"style=simple,explode=false,name=modelId"`
}

type UpdateModelResponse struct {
	ContentType string
	// Something went wrong
	InternalServerError *shared.InternalServerErrorEnum
	StatusCode          int
	RawResponse         *http.Response
	// Ok
	UpdateModel200ApplicationJSONAnyOf interface{}
	// Validation Failed
	ValidateErrorJSON *shared.ValidateErrorJSON
}
