// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"fmt"
)

type Message string

const (
	MessageValidationFailed Message = "Validation failed"
)

func (e Message) ToPointer() *Message {
	return &e
}

func (e *Message) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Validation failed":
		*e = Message(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Message: %v", v)
	}
}

type ValidateErrorJSON struct {
	Details map[string]interface{} `json:"details"`
	Message Message                `json:"message"`
}

var _ error = &ValidateErrorJSON{}

func (e *ValidateErrorJSON) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
