// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/hightouch-go-sdk/pkg/utils"
)

type DBTScheduleAccount struct {
	ID string `json:"id"`
}

func (o *DBTScheduleAccount) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type DBTScheduleJob struct {
	ID string `json:"id"`
}

func (o *DBTScheduleJob) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type DBTSchedule struct {
	AdditionalProperties map[string]interface{} `additionalProperties:"true" json:"-"`
	Account              DBTScheduleAccount     `json:"account"`
	Job                  DBTScheduleJob         `json:"job"`
}

func (d DBTSchedule) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DBTSchedule) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *DBTSchedule) GetAdditionalProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *DBTSchedule) GetAccount() DBTScheduleAccount {
	if o == nil {
		return DBTScheduleAccount{}
	}
	return o.Account
}

func (o *DBTSchedule) GetJob() DBTScheduleJob {
	if o == nil {
		return DBTScheduleJob{}
	}
	return o.Job
}
