// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/hightouch-go-sdk/pkg/utils"
)

// DestinationCreate - The input for creating a Destination
type DestinationCreate struct {
	AdditionalProperties map[string]interface{} `additionalProperties:"true" json:"-"`
	// The destination's configuration. This specifies general metadata about destination, like hostname and username.
	// Hightouch will be using this configuration to connect to destination.
	//
	// The schema depends on the destination type.
	//
	// Consumers should NOT make assumptions on the contents of the
	// configuration. It may change as Hightouch updates its internal code.
	Configuration map[string]interface{} `json:"configuration"`
	// The destination's name
	Name string `json:"name"`
	// The destination's slug
	Slug string `json:"slug"`
	// The destination's type (e.g. salesforce or hubspot).
	Type string `json:"type"`
}

func (d DestinationCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DestinationCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *DestinationCreate) GetAdditionalProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *DestinationCreate) GetConfiguration() map[string]interface{} {
	if o == nil {
		return map[string]interface{}{}
	}
	return o.Configuration
}

func (o *DestinationCreate) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *DestinationCreate) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *DestinationCreate) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}
