// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/hightouch-go-sdk/pkg/utils"
)

// DestinationUpdate - The input for updating a Destination
type DestinationUpdate struct {
	AdditionalProperties map[string]interface{} `additionalProperties:"true" json:"-"`
	// The destination's configuration. This specifies general metadata about destination, like hostname and username.
	// Hightouch will be using this configuration to connect to destination.
	//
	// The schema depends on the destination type.
	//
	// Consumers should NOT make assumptions on the contents of the
	// configuration. It may change as Hightouch updates its internal code.
	Configuration map[string]interface{} `json:"configuration,omitempty"`
	// The destination's name
	Name *string `json:"name,omitempty"`
}

func (d DestinationUpdate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DestinationUpdate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *DestinationUpdate) GetAdditionalProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *DestinationUpdate) GetConfiguration() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.Configuration
}

func (o *DestinationUpdate) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
