// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/hightouch-go-sdk/pkg/utils"
	"time"
)

// Destination - The service receiving your data (e.g. Salesforce, Hubspot, Customer.io, or a
// SFTP server)
type Destination struct {
	// The destination's configuration. This specifies general metadata about destination, like hostname and username.
	// Hightouch will be using this configuration to connect to destination.
	//
	// The schema depends on the destination type.
	//
	// Consumers should NOT make assumptions on the contents of the
	// configuration. It may change as Hightouch updates its internal code.
	Configuration map[string]interface{} `json:"configuration"`
	// The timestamp when the destination was created
	CreatedAt time.Time `json:"createdAt"`
	// The destination's id
	ID float64 `json:"id"`
	// The destination's name
	Name string `json:"name"`
	// The destination's slug
	Slug string `json:"slug"`
	// A list of syncs that sync to this destination.
	Syncs []float64 `json:"syncs"`
	// The destination's type (e.g. salesforce or hubspot).
	Type string `json:"type"`
	// The timestamp when the destination was last updated
	UpdatedAt time.Time `json:"updatedAt"`
	// The id of the workspace that the destination belongs to
	WorkspaceID float64 `json:"workspaceId"`
}

func (d Destination) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *Destination) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *Destination) GetConfiguration() map[string]interface{} {
	if o == nil {
		return map[string]interface{}{}
	}
	return o.Configuration
}

func (o *Destination) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *Destination) GetID() float64 {
	if o == nil {
		return 0.0
	}
	return o.ID
}

func (o *Destination) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Destination) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *Destination) GetSyncs() []float64 {
	if o == nil {
		return []float64{}
	}
	return o.Syncs
}

func (o *Destination) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *Destination) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *Destination) GetWorkspaceID() float64 {
	if o == nil {
		return 0.0
	}
	return o.WorkspaceID
}
