// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// InternalServerErrorEnum - Something went wrong
type InternalServerErrorEnum string

const (
	InternalServerErrorEnumInternalServerError InternalServerErrorEnum = "Internal Server Error"
)

func (e InternalServerErrorEnum) ToPointer() *InternalServerErrorEnum {
	return &e
}

func (e *InternalServerErrorEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Internal Server Error":
		*e = InternalServerErrorEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InternalServerErrorEnum: %v", v)
	}
}
