// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/hightouch-go-sdk/pkg/utils"
)

type Interval struct {
	AdditionalProperties map[string]interface{} `additionalProperties:"true" json:"-"`
	Quantity             float64                `json:"quantity"`
	Unit                 IntervalUnit           `json:"unit"`
}

func (i Interval) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *Interval) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Interval) GetAdditionalProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *Interval) GetQuantity() float64 {
	if o == nil {
		return 0.0
	}
	return o.Quantity
}

func (o *Interval) GetUnit() IntervalUnit {
	if o == nil {
		return IntervalUnit("")
	}
	return o.Unit
}
