// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// InternalServerError - Something went wrong
type InternalServerError string

const (
	InternalServerErrorInternalServerError InternalServerError = "Internal Server Error"
)

func (e InternalServerError) ToPointer() *InternalServerError {
	return &e
}

func (e *InternalServerError) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Internal Server Error":
		*e = InternalServerError(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InternalServerError: %v", v)
	}
}
