// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type IntervalUnitEnum string

const (
	IntervalUnitEnumMinute IntervalUnitEnum = "minute"
	IntervalUnitEnumHour   IntervalUnitEnum = "hour"
	IntervalUnitEnumDay    IntervalUnitEnum = "day"
	IntervalUnitEnumWeek   IntervalUnitEnum = "week"
)

func (e IntervalUnitEnum) ToPointer() *IntervalUnitEnum {
	return &e
}

func (e *IntervalUnitEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "minute":
		fallthrough
	case "hour":
		fallthrough
	case "day":
		fallthrough
	case "week":
		*e = IntervalUnitEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntervalUnitEnum: %v", v)
	}
}
