// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type IntervalUnitEnum string

const (
	IntervalUnitEnumMinute IntervalUnitEnum = "minute"
	IntervalUnitEnumHour   IntervalUnitEnum = "hour"
	IntervalUnitEnumDay    IntervalUnitEnum = "day"
	IntervalUnitEnumWeek   IntervalUnitEnum = "week"
)
