// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ModelCreateCustom - Custom query for sources that doesn't support sql. For example, Airtable.
type ModelCreateCustom struct {
	Query interface{} `json:"query"`
}

type ModelCreateDbt struct {
	// Number as a string
	ModelID string `json:"modelId"`
}

// ModelCreateRaw - Standard raw SQL query
type ModelCreateRaw struct {
	SQL string `json:"sql"`
}

// ModelCreateTable - Table-based query that fetches on a table instead of SQL
type ModelCreateTable struct {
	Name string `json:"name"`
}

// ModelCreateVisual - Visual query, used by audience
type ModelCreateVisual struct {
	Filter interface{} `json:"filter"`
	// Number as a string
	ParentID       string `json:"parentId"`
	PrimaryLabel   string `json:"primaryLabel"`
	SecondaryLabel string `json:"secondaryLabel"`
}

// ModelCreate - The input for creating a Model
type ModelCreate struct {
	// Custom query for sources that doesn't support sql. For example, Airtable.
	Custom *ModelCreateCustom `json:"custom,omitempty"`
	Dbt    *ModelCreateDbt    `json:"dbt,omitempty"`
	// If is_schema is true, the model is just used to build other models.
	// Either as part of visual querying, or as the root of a visual query.
	IsSchema bool `json:"isSchema"`
	// The name of the model
	Name string `json:"name"`
	// The primary key will be null if the query doesn't get directly synced (e.g. a relationship table for visual querying)
	PrimaryKey string `json:"primaryKey"`
	// The type of the query. Available options: custom, raw_sql, tabel, dbt and visual.
	QueryType string `json:"queryType"`
	// Standard raw SQL query
	Raw *ModelCreateRaw `json:"raw,omitempty"`
	// The slug of the model
	Slug string `json:"slug"`
	// Number as a string
	SourceID string `json:"sourceId"`
	// Table-based query that fetches on a table instead of SQL
	Table *ModelCreateTable `json:"table,omitempty"`
	// Visual query, used by audience
	Visual *ModelCreateVisual `json:"visual,omitempty"`
}
