// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/hightouch-go-sdk/pkg/utils"
)

// SourceCreate - The input for creating a Source
type SourceCreate struct {
	AdditionalProperties map[string]interface{} `additionalProperties:"true" json:"-"`
	// The source's configuration. This specifies general metadata about sources, like connection details
	// Hightouch will use this configuration to connect to underlying source.
	//
	// The schema depends on the source type.
	//
	// Consumers should NOT make assumptions on the contents of the
	// configuration. It may change as Hightouch updates its internal code.
	Configuration map[string]interface{} `json:"configuration"`
	// The source's name
	Name string `json:"name"`
	// The source's slug
	Slug string `json:"slug"`
	// The source's type (e.g. snowflake or postgres).
	Type string `json:"type"`
}

func (s SourceCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SourceCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SourceCreate) GetAdditionalProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *SourceCreate) GetConfiguration() map[string]interface{} {
	if o == nil {
		return map[string]interface{}{}
	}
	return o.Configuration
}

func (o *SourceCreate) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *SourceCreate) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *SourceCreate) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}
