// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"errors"
	"github.com/speakeasy-sdks/hightouch-go-sdk/pkg/utils"
)

type SyncCreateSchemasScheduleType string

const (
	SyncCreateSchemasScheduleTypeIntervalSchedule   SyncCreateSchemasScheduleType = "IntervalSchedule"
	SyncCreateSchemasScheduleTypeCronSchedule       SyncCreateSchemasScheduleType = "CronSchedule"
	SyncCreateSchemasScheduleTypeVisualCronSchedule SyncCreateSchemasScheduleType = "VisualCronSchedule"
	SyncCreateSchemasScheduleTypeDBTSchedule        SyncCreateSchemasScheduleType = "DBTSchedule"
)

type SyncCreateSchemasSchedule struct {
	IntervalSchedule   *IntervalSchedule
	CronSchedule       *CronSchedule
	VisualCronSchedule *VisualCronSchedule
	DBTSchedule        *DBTSchedule

	Type SyncCreateSchemasScheduleType
}

func CreateSyncCreateSchemasScheduleIntervalSchedule(intervalSchedule IntervalSchedule) SyncCreateSchemasSchedule {
	typ := SyncCreateSchemasScheduleTypeIntervalSchedule

	return SyncCreateSchemasSchedule{
		IntervalSchedule: &intervalSchedule,
		Type:             typ,
	}
}

func CreateSyncCreateSchemasScheduleCronSchedule(cronSchedule CronSchedule) SyncCreateSchemasSchedule {
	typ := SyncCreateSchemasScheduleTypeCronSchedule

	return SyncCreateSchemasSchedule{
		CronSchedule: &cronSchedule,
		Type:         typ,
	}
}

func CreateSyncCreateSchemasScheduleVisualCronSchedule(visualCronSchedule VisualCronSchedule) SyncCreateSchemasSchedule {
	typ := SyncCreateSchemasScheduleTypeVisualCronSchedule

	return SyncCreateSchemasSchedule{
		VisualCronSchedule: &visualCronSchedule,
		Type:               typ,
	}
}

func CreateSyncCreateSchemasScheduleDBTSchedule(dbtSchedule DBTSchedule) SyncCreateSchemasSchedule {
	typ := SyncCreateSchemasScheduleTypeDBTSchedule

	return SyncCreateSchemasSchedule{
		DBTSchedule: &dbtSchedule,
		Type:        typ,
	}
}

func (u *SyncCreateSchemasSchedule) UnmarshalJSON(data []byte) error {

	intervalSchedule := IntervalSchedule{}
	if err := utils.UnmarshalJSON(data, &intervalSchedule, "", true, true); err == nil {
		u.IntervalSchedule = &intervalSchedule
		u.Type = SyncCreateSchemasScheduleTypeIntervalSchedule
		return nil
	}

	cronSchedule := CronSchedule{}
	if err := utils.UnmarshalJSON(data, &cronSchedule, "", true, true); err == nil {
		u.CronSchedule = &cronSchedule
		u.Type = SyncCreateSchemasScheduleTypeCronSchedule
		return nil
	}

	visualCronSchedule := VisualCronSchedule{}
	if err := utils.UnmarshalJSON(data, &visualCronSchedule, "", true, true); err == nil {
		u.VisualCronSchedule = &visualCronSchedule
		u.Type = SyncCreateSchemasScheduleTypeVisualCronSchedule
		return nil
	}

	dbtSchedule := DBTSchedule{}
	if err := utils.UnmarshalJSON(data, &dbtSchedule, "", true, true); err == nil {
		u.DBTSchedule = &dbtSchedule
		u.Type = SyncCreateSchemasScheduleTypeDBTSchedule
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u SyncCreateSchemasSchedule) MarshalJSON() ([]byte, error) {
	if u.IntervalSchedule != nil {
		return utils.MarshalJSON(u.IntervalSchedule, "", true)
	}

	if u.CronSchedule != nil {
		return utils.MarshalJSON(u.CronSchedule, "", true)
	}

	if u.VisualCronSchedule != nil {
		return utils.MarshalJSON(u.VisualCronSchedule, "", true)
	}

	if u.DBTSchedule != nil {
		return utils.MarshalJSON(u.DBTSchedule, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

// SyncCreateSchedule - The scheduling configuration. It can be triggerd based on several ways:
//
// Interval: the sync will be trigged based on certain interval(minutes/hours/days/weeks)
//
// Cron: the sync will be trigged based on cron expression https://en.wikipedia.org/wiki/Cron.
//
// Visual: the sync will be trigged based a visual cron configuration on UI
//
// DBT-cloud: the sync will be trigged based on a dbt cloud job
type SyncCreateSchedule struct {
	Schedule SyncCreateSchemasSchedule `json:"schedule"`
	Type     string                    `json:"type"`
}

func (o *SyncCreateSchedule) GetSchedule() SyncCreateSchemasSchedule {
	if o == nil {
		return SyncCreateSchemasSchedule{}
	}
	return o.Schedule
}

func (o *SyncCreateSchedule) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

// SyncCreate - The input for creating a Sync
type SyncCreate struct {
	// The sync's configuration. This specifies how data is mapped, among other
	// configuration.
	//
	// The schema depends on the destination type.
	//
	// Consumers should NOT make assumptions on the contents of the
	// configuration. It may change as Hightouch updates its internal code.
	Configuration map[string]interface{} `json:"configuration"`
	// The id of the Destination that sync is connected to
	DestinationID float64 `json:"destinationId"`
	// Whether the sync has been disabled by the user.
	Disabled bool `json:"disabled"`
	// The id of the Model that sync is connected to
	ModelID float64 `json:"modelId"`
	// The scheduling configuration. It can be triggerd based on several ways:
	//
	// Interval: the sync will be trigged based on certain interval(minutes/hours/days/weeks)
	//
	// Cron: the sync will be trigged based on cron expression https://en.wikipedia.org/wiki/Cron.
	//
	// Visual: the sync will be trigged based a visual cron configuration on UI
	//
	// DBT-cloud: the sync will be trigged based on a dbt cloud job
	Schedule *SyncCreateSchedule `json:"schedule"`
	// The sync's slug
	Slug string `json:"slug"`
}

func (o *SyncCreate) GetConfiguration() map[string]interface{} {
	if o == nil {
		return map[string]interface{}{}
	}
	return o.Configuration
}

func (o *SyncCreate) GetDestinationID() float64 {
	if o == nil {
		return 0.0
	}
	return o.DestinationID
}

func (o *SyncCreate) GetDisabled() bool {
	if o == nil {
		return false
	}
	return o.Disabled
}

func (o *SyncCreate) GetModelID() float64 {
	if o == nil {
		return 0.0
	}
	return o.ModelID
}

func (o *SyncCreate) GetSchedule() *SyncCreateSchedule {
	if o == nil {
		return nil
	}
	return o.Schedule
}

func (o *SyncCreate) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}
