// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/hightouch-go-sdk/pkg/utils"
)

// TriggerRunInput - The input of a trigger action to run syncs
type TriggerRunInput struct {
	// Whether to resync all the rows in the query (i.e. ignoring previously
	// synced rows).
	FullResync *bool `default:"false" json:"fullResync"`
	// Whether to sync all the rows in the query without executing changes on the destination.
	ResetCDC *bool `default:"false" json:"resetCDC"`
}

func (t TriggerRunInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TriggerRunInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TriggerRunInput) GetFullResync() *bool {
	if o == nil {
		return nil
	}
	return o.FullResync
}

func (o *TriggerRunInput) GetResetCDC() *bool {
	if o == nil {
		return nil
	}
	return o.ResetCDC
}
