// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// TriggerRunCustomInput - The input of a trigger action to run syncs based on sync ID, slug or other filters
type TriggerRunCustomInput struct {
	// Whether to resync all the rows in the query (i.e. ignoring previously
	// synced rows).
	FullResync *bool `json:"fullResync,omitempty"`
	// Trigger run based on sync id
	SyncID *string `json:"syncId,omitempty"`
	// Trigger run based on sync slug
	SyncSlug *string `json:"syncSlug,omitempty"`
}
