// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// TriggerRunOutput - The output of a trigger action to run syncs
type TriggerRunOutput struct {
	// The id of the triggered sync run. This can be passed to `/sync/runs` to
	// get the run's status.
	ID string `json:"id"`
}
