// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// TriggerRunIDGraphInput - The input of a trigger action to run IDR.
type TriggerRunIDGraphInput struct {
	// Whether to resync the entire Identity Graph or process incrementally.
	FullRerun *bool `json:"fullRerun,omitempty"`
}
