// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ValidateErrorJSONMessageEnum string

const (
	ValidateErrorJSONMessageEnumValidationFailed ValidateErrorJSONMessageEnum = "Validation failed"
)

// ValidateErrorJSON - Validation Failed
type ValidateErrorJSON struct {
	Details map[string]interface{}       `json:"details"`
	Message ValidateErrorJSONMessageEnum `json:"message"`
}
