// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Expressions struct {
	// Construct a type with a set of properties K of type T
	Days RecordDayBooleanOrUndefined `json:"days"`
	Time string                      `json:"time"`
}

func (o *Expressions) GetDays() RecordDayBooleanOrUndefined {
	if o == nil {
		return RecordDayBooleanOrUndefined{}
	}
	return o.Days
}

func (o *Expressions) GetTime() string {
	if o == nil {
		return ""
	}
	return o.Time
}

type VisualCronSchedule struct {
	Expressions []Expressions `json:"expressions"`
}

func (o *VisualCronSchedule) GetExpressions() []Expressions {
	if o == nil {
		return []Expressions{}
	}
	return o.Expressions
}
