// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type VisualCronScheduleExpressions struct {
	// Construct a type with a set of properties K of type T
	Days RecordDayBooleanOrUndefined `json:"days"`
	Time string                      `json:"time"`
}

func (o *VisualCronScheduleExpressions) GetDays() RecordDayBooleanOrUndefined {
	if o == nil {
		return RecordDayBooleanOrUndefined{}
	}
	return o.Days
}

func (o *VisualCronScheduleExpressions) GetTime() string {
	if o == nil {
		return ""
	}
	return o.Time
}

type VisualCronSchedule struct {
	Expressions []VisualCronScheduleExpressions `json:"expressions"`
}

func (o *VisualCronSchedule) GetExpressions() []VisualCronScheduleExpressions {
	if o == nil {
		return []VisualCronScheduleExpressions{}
	}
	return o.Expressions
}
